pub type OpCode = u8;

#[derive(Copy, Clone)]
pub enum Mnemonic {
    Adc,
    Anc,
    And,
    Ane,
    Arr,
    Asl,
    Asr,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dcp,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Isc,
    Jam,
    Jmp,
    Jsr,
    Las,
    Lax,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Lxa,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rla,
    Rol,
    Ror,
    Rra,
    Rti,
    Rts,
    Sax,
    Sbc,
    Sbx,
    Sec,
    Sed,
    Sei,
    Sha,
    Shx,
    Shy,
    Slo,
    Sre,
    Sta,
    Stx,
    Sty,
    Tas,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
}

impl From<OpCode> for Mnemonic {
    fn from(opcode: OpCode) -> Self {
        JUMP_TABLE[opcode as usize]
    }
}

use Mnemonic::*;
pub static JUMP_TABLE: [Mnemonic; 256] = [
    Brk, Ora, Jam, Slo, Nop, Ora, Asl, Slo, Php, Ora, Asl, Anc, Nop, Ora, Asl, Slo, Bpl, Ora, Jam,
    Slo, Nop, Ora, Asl, Slo, Clc, Ora, Nop, Slo, Nop, Ora, Asl, Slo, Jsr, And, Jam, Rla, Bit, And,
    Rol, Rla, Plp, And, Rol, Anc, Bit, And, Rol, Rla, Bmi, And, Jam, Rla, Nop, And, Rol, Rla, Sec,
    And, Nop, Rla, Nop, And, Rol, Rla, Rti, Eor, Jam, Sre, Nop, Eor, Lsr, Sre, Pha, Eor, Lsr, Asr,
    Jmp, Eor, Lsr, Sre, Bvc, Eor, Jam, Sre, Nop, Eor, Lsr, Sre, Cli, Eor, Nop, Sre, Nop, Eor, Lsr,
    Sre, Rts, Adc, Jam, Rra, Nop, Adc, Ror, Rra, Pla, Adc, Ror, Arr, Jmp, Adc, Ror, Rra, Bvs, Adc,
    Jam, Rra, Nop, Adc, Ror, Rra, Sei, Adc, Nop, Rra, Nop, Adc, Ror, Rra, Nop, Sta, Nop, Sax, Sty,
    Sta, Stx, Sax, Dey, Nop, Txa, Ane, Sty, Sta, Stx, Sax, Bcc, Sta, Jam, Sha, Sty, Sta, Stx, Sax,
    Tya, Sta, Txs, Tas, Shy, Sta, Shx, Sha, Ldy, Lda, Ldx, Lax, Ldy, Lda, Ldx, Lax, Tay, Lda, Tax,
    Lxa, Ldy, Lda, Ldx, Lax, Bcs, Lda, Jam, Lax, Ldy, Lda, Ldx, Lax, Clv, Lda, Tsx, Las, Ldy, Lda,
    Ldx, Lax, Cpy, Cmp, Nop, Dcp, Cpy, Cmp, Dec, Dcp, Iny, Cmp, Dex, Sbx, Cpy, Cmp, Dec, Dcp, Bne,
    Cmp, Jam, Dcp, Nop, Cmp, Dec, Dcp, Cld, Cmp, Nop, Dcp, Nop, Cmp, Dec, Dcp, Cpx, Sbc, Nop, Isc,
    Cpx, Sbc, Inc, Isc, Inx, Sbc, Nop, Sbc, Cpx, Sbc, Inc, Isc, Beq, Sbc, Jam, Isc, Nop, Sbc, Inc,
    Isc, Sed, Sbc, Nop, Isc, Nop, Sbc, Inc, Isc,
];
